add GET requests for transactions
QAM-ATC/poandy pull request #19
Opened 2021-02-14 05:01 UTC by Tigeronz

will figure out how to write the test file and the stream function later.

2021-02-18 07:10 UTC, wowweijie approved these changes
looks good

2021-03-05 15:49 UTC, Tigeronz commented
All functions, tests, and demo files are done

2021-03-07 04:00 UTC, kaneishere requested changes
Nice work! @callistachang pls review as well

2021-03-07 04:00 UTC, kaneishere commented on poandy/controller/transactions.py
> +                "MARKET_ORDER", "MARKET_ORDER_REJECT", "LIMIT_ORDER", "LIMIT_ORDER_REJECT", "STOP_ORDER", "STOP_ORDER_REJECT", "MARKET_IF_TOUCHED_ORDER", "MARKET_IF_TOUCHED_ORDER_REJECT",
I think we should factor out this into a file and load it, like the config.json file

2021-03-07 04:00 UTC, kaneishere commented on poandy/controller/transactions.py
> +        if filter_types:
I think this chunk of code has been appearing frequently enough for you to factor it out into a function

2021-03-07 04:00 UTC, kaneishere commented on poandy/controller/transactions.py
> +        if filter_types:
maybe something like validate_filter_types(filter_types: List[str]) -> str

2021-03-07 04:00 UTC, kaneishere commented on poandy/controller/transactions.py
> +            print(line)
I think this chunk of code should be in the notebook and left for the client to do

2021-03-07 04:00 UTC, kaneishere commented on tests/test_transactions.py
> +        account_id = AccountController.get_default_account_id()
factor out the account_id into the scope of the class instead of having to instantiate it in every function

2021-03-07 04:00 UTC, kaneishere commented on tests/test_transactions.py
> +        assert isinstance(account_id, str)
This line is not required. Because this should already be covered under the tests for AccountController.

2021-03-07 07:44 UTC, Tigeronz commented on poandy/controller/transactions.py
> +            print(line)
so I should just return the stream_response object, right?

2021-03-07 08:23 UTC, Tigeronz commented on tests/test_transactions.py
> +        account_id = AccountController.get_default_account_id()
pytest doesn't seem to use global variables...? I'd have to use fixtures instead but that basically calls AccountController.get_default_account_id() every time anyway...
At least that's what I found on stack overflow. Apparently, they don't encourage global variables.

2021-03-07 09:03 UTC, Tigeronz commented on poandy/controller/transactions.py
> +                "MARKET_ORDER", "MARKET_ORDER_REJECT", "LIMIT_ORDER", "LIMIT_ORDER_REJECT", "STOP_ORDER", "STOP_ORDER_REJECT", "MARKET_IF_TOUCHED_ORDER", "MARKET_IF_TOUCHED_ORDER_REJECT",
done!

2021-03-07 09:03 UTC, Tigeronz commented on poandy/controller/transactions.py
> +        if filter_types:
done

2021-03-07 09:03 UTC, Tigeronz commented on poandy/controller/transactions.py
> +            print(line)
done

2021-03-07 09:03 UTC, Tigeronz commented on tests/test_transactions.py
> +        assert isinstance(account_id, str)
done

2021-03-07 09:15 UTC, Tigeronz commented on tests/test_transactions.py
> +        account_id = AccountController.get_default_account_id()
done

2021-03-07 13:26 UTC, callistachang commented
Sorry for the late review @Tigeronz 😃

Everything looks good, apart from a small nitpick - was wondering if you would like to rename the file from `transactions.py` to `transaction.py` and `TransactionsController` to `TransactionController` for it to be consistent with the rest of the files. Otherwise great job!

2021-03-07 13:26 UTC, callistachang reviewed
Sorry for the late review @Tigeronz 😃

Everything looks good, apart from a small nitpick - was wondering if you would like to rename the file from transactions.py to transaction.py and TransactionsController to TransactionController for it to be consistent with the rest of the files. Otherwise great job!

2021-03-07 13:33 UTC, callistachang requested changes
Sorry I accidentally self-requested a review

2021-03-08 01:31 UTC, kaneishere commented on poandy/controller/transaction.py
> +        for ftype in filter_types:
Small nitpick - if the function is never going to return false (it's either throwing an exception or returning true) then there's no point for it to return True

2021-03-08 01:34 UTC, kaneishere approved these changes
Looks good to me, once you've addressed the comment I left, please squash your commits into a single commit before pushing
```
git reset --soft <sha of the commit right before your issue> && git commit -am "Name of your issue"
```
```
git push -f
```

2021-03-13 01:52 UTC, callistachang approved these changes

2021-03-15 01:19 UTC, merged